// packages/vue/src/TWallpaper.vue
<script setup lang="ts">
import { TWallpaper } from 'twallpaper'
import type { TWallpaperOptions } from 'twallpaper'
import 'twallpaper/css'
import { PropType, Ref, defineExpose, onMounted, onUnmounted, ref } from 'vue'

const props = defineProps({
  options: {
    type: Object as PropType<TWallpaperOptions>,
    required: false
  }
})

const container = ref<HTMLDivElement | null>(null)
const twallpaper = new TWallpaper()

defineExpose<{
  container: Ref<HTMLDivElement | null>
  twallpaper: TWallpaper
}>({
  container,
  twallpaper
})

onMounted(() => {
  twallpaper.init(
    {
      colors: twallpaper.generateColors(),
      ...props.options
    },
    container.value!
  )
})

onUnmounted(() => {
  twallpaper.dispose()
})
</script>

<template>
  <div ref="container"></div>
</template>

// examples/with-react-component/src/TWallpaper.tsx
import { TWallpaper as TW } from 'twallpaper'
import type { TWallpaperOptions } from 'twallpaper'
import 'twallpaper/css'
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'

export interface TWallpaperProps {
  options?: TWallpaperOptions
}

export interface TWallpaperHandlers {
  toNextPosition: () => void
}

const TWallpaper = forwardRef<TWallpaperHandlers, TWallpaperProps>(
  ({ options }, ref) => {
    const container = useRef<HTMLDivElement>(null)
    const twallpaper = useRef<TW>()

    useImperativeHandle(ref, () => ({
      toNextPosition() {
        twallpaper.current!.toNextPosition()
      }
    }))

    useEffect(() => {
      if (!twallpaper.current) {
        twallpaper.current = new TW(container.current!)
      }

      twallpaper.current.init({
        colors: twallpaper.current.generateColors(),
        ...options
      })

      return () => {
        twallpaper.current!.dispose()
      }
    }, [options])

    return <div ref={container}></div>
  }
)

export { TWallpaper }
export default TWallpaper
export type { TWallpaperOptions }
